# Generated by Django 4.0.5 on 2022-07-06 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='user_email')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Venue_name')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('zip_code', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('web', models.URLField()),
                ('email_Address', models.EmailField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='main.myclubuser'),
        ),
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.venue'),
        ),
    ]
