# Generated by Django 4.0.5 on 2022-07-07 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_events_venue_alter_events_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.venue'),
        ),
    ]
