# Generated by Django 4.0.5 on 2022-07-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_venue_owner_alter_events_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(max_length=200, verbose_name='event_date'),
        ),
    ]
