# Generated by Django 4.0.5 on 2022-07-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_venue_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Aprroved'),
        ),
    ]
