# Generated by Django 4.0.5 on 2022-07-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_events_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
    ]
